name: gyawun
description: Flutter application for streaming music from Jio Saavn
publish_to: 'none'
version: 0.9.5+14

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:    
    sdk: flutter
  audio_service: ^0.18.10
  audio_video_progress_bar: ^1.0.1
  dart_des: ^1.0.2
  eva_icons_flutter: ^3.1.0
  get_it: ^7.6.0
  go_router: ^8.2.0
  google_fonts: any
  http: any
  iconsax: ^0.0.8
  just_audio: ^0.9.34
  provider: ^6.0.5
  sliding_up_panel: ^2.0.0+1
  logging: any
  duration_picker: ^1.1.1
  flutter_displaymode: ^0.6.0
  flutter_swipe_action_cell: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.0.3
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.2.3
  dynamic_color: ^1.6.5
  flutter_lyric: ^2.0.4+6
  flip_card: ^0.7.0
  permission_handler: ^10.4.1

  flutter_progress_status: ^0.0.3
  path_provider: ^2.0.15
  youtube_explode_dart: ^2.0.2
  auto_size_text: ^3.0.0
  skeletons: ^0.0.3
  country_picker: ^2.0.20
  intl: any
  shared_preferences: ^2.2.0
  audio_tagger:
    git:
      url: https://github.com/SongTube/audio_tagger
      ref: main
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/icon.png
flutter_intl:
  enabled: true

