name: gyawun_music
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=3.9.0 <4.0.0"
description: A new Flutter project.
dependencies:
  audio_service: ^0.18.18
  audio_service_mpris: ^0.2.0
  audio_service_win: ^0.0.2
  audio_session: ^0.2.2
  audio_video_progress_bar: ^2.0.3
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  dynamic_color: ^1.7.0
  expandable_page_view: ^1.0.17
  expressive_refresh: ^0.1.2
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.2
  get_it: ^9.0.5
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  http: ^1.5.0
  image: ^4.5.4
  intl: ^0.20.2
  just_audio: ^0.10.5
  just_audio_media_kit: ^2.1.0
  lottie: ^3.3.2
  m3e_design: ^0.2.1
  media_kit_libs_linux: any
  meta: ^1.16.0
  navigation_bar_m3e: ^0.1.1
  navigation_rail_flutter: ^1.0.3
  navigation_rail_m3e: ^0.3.5
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  playlist_manager:
    git: https://github.com/sheikhhaziq/playlist_manager.git
  readmore: ^3.0.0
  rxdart: ^0.28.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  slider_m3e: ^0.1.1
  sliver_tools: ^0.2.12
  url_launcher: ^6.3.2
  youtube_explode_dart: ^3.0.0
  ytmusic:
    path: ../ytmusic
dev_dependencies:
  build_runner: ^2.10.1
  drift_dev: ^2.29.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/svgs/
  fonts:
    - family: paytoneOne
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf

